export const welcomeStyles = {
  root: 'min-h-screen bg-[#000000] text-neutral-200 flex flex-col lg:flex-row font-sans selection:bg-white selection:text-black',
  gridBackground: 'hidden',
  leftCol: 'w-full lg:w-1/2 p-8 lg:p-20 flex flex-col justify-between border-b lg:border-b-0 lg:border-r border-neutral-900 min-h-[50vh] lg:min-h-screen',
  rightCol: 'w-full lg:w-1/2 p-8 lg:p-20 flex flex-col justify-center bg-[#050505] min-h-[50vh] lg:min-h-screen',
  logo: 'flex items-center text-white',
  title: 'text-5xl lg:text-7xl font-semibold tracking-tighter text-white leading-[1.1] mt-auto',
  subtitle: 'text-neutral-500 text-base max-w-sm mt-8 leading-relaxed mb-auto',
  buttonPrimary: 'w-full px-6 py-4 bg-white hover:bg-neutral-200 text-sm font-bold text-black transition-all flex items-center justify-between group',
  buttonSecondary: 'w-full px-6 py-4 bg-transparent border border-neutral-800 hover:border-neutral-600 text-sm font-bold text-white transition-all flex items-center justify-between group mt-3',
  featureGrid: 'grid grid-cols-1 gap-10 mt-16',
  featureCard: 'flex flex-col gap-2',
  featureTitle: 'text-sm font-bold text-white flex items-center gap-3',
  featureDesc: 'text-sm text-neutral-500 leading-relaxed max-w-md',
};
