export const headerStyles = {
  header: 'flex flex-col lg:flex-row lg:items-center justify-between gap-5 border-b border-neutral-800/80 pb-6',
  brandCol: 'flex flex-col gap-1',
  topBadgeRow: 'flex items-center gap-2.5',
  atlasBadge: 'px-2.5 py-0.5 rounded-full text-[10px] font-bold tracking-wide uppercase bg-emerald-500/10 text-emerald-400 border border-emerald-500/25 flex items-center gap-1.5 shadow-sm',
  titleRow: 'flex items-center gap-3 mt-1',
  title: 'text-2xl sm:text-3xl font-semibold tracking-tight text-white',
  subtitle: 'text-xs text-neutral-400 max-w-md leading-relaxed',
  actionsCol: 'flex flex-wrap items-center gap-3',
  selectWrap: 'relative',
  select: 'appearance-none bg-[#050505] border border-neutral-800 hover:border-neutral-700 rounded-none px-4 py-2 pr-9 text-xs font-bold text-neutral-200 focus:outline-none focus:border-white cursor-pointer shadow-sm transition-all',
  authBtn: 'px-4 py-2 rounded-none bg-white hover:bg-neutral-200 text-black font-bold text-xs transition-all active:scale-95 flex items-center gap-1.5',
  userChip: 'flex items-center gap-2 px-3 py-1.5 rounded-none bg-transparent border border-neutral-800 text-xs font-bold text-neutral-300',
  logoutBtn: 'p-1.5 rounded-none hover:bg-neutral-900 text-neutral-400 hover:text-white transition-colors border border-transparent hover:border-neutral-800',
};
