export const threeDStyles = {
  container: 'w-full mb-6',
  cardWrap: 'relative w-full rounded-none border border-neutral-800/80 bg-[#050508] overflow-hidden',
  cardGradient: '',
  innerCard: 'relative w-full rounded-none p-6 flex flex-col gap-5 overflow-hidden',
  shineOverlay: 'pointer-events-none absolute inset-0 opacity-30 mix-blend-screen bg-[radial-gradient(ellipse_at_top_left,rgba(56,189,248,0.07)_0%,transparent_60%),radial-gradient(ellipse_at_bottom_right,rgba(168,85,247,0.07)_0%,transparent_60%)]',
  badgeRow: 'flex items-center justify-between',
  networkBadge: 'px-3 py-1.5 rounded-none text-[10px] font-bold uppercase tracking-widest border flex items-center gap-2',
  evmBadge: 'bg-sky-500/10 text-sky-300 border-sky-500/30',
  solanaBadge: 'bg-violet-500/10 text-violet-300 border-violet-500/30',
  addressBox: 'p-4 rounded-none bg-[#0a0a0e] border border-neutral-800/80 flex items-center justify-between gap-3 group hover:border-sky-500/20 transition-colors',
  addressText: 'font-mono text-sm text-neutral-300 truncate select-all',
  copyBtn: 'px-3 py-1.5 rounded-none bg-neutral-800/80 hover:bg-sky-500/10 hover:text-sky-300 hover:border-sky-500/30 border border-neutral-700 text-neutral-200 transition-colors shrink-0 text-xs font-bold uppercase tracking-widest',
  actionRow: 'flex flex-wrap items-center gap-2 pt-2',
  chipBtn: 'px-4 py-2 rounded-none bg-transparent border border-neutral-800 hover:bg-indigo-500/5 hover:border-indigo-500/30 hover:text-indigo-300 text-xs font-bold uppercase tracking-widest text-neutral-400 transition-all',
  faucetBtn: 'px-4 py-2 rounded-none bg-gradient-to-r from-violet-600/80 to-fuchsia-600/80 hover:from-violet-500/90 hover:to-fuchsia-500/90 text-white text-xs font-bold uppercase tracking-widest transition-all active:scale-95 disabled:opacity-40 flex items-center gap-2 border border-violet-500/20',
  phraseCard: 'mt-2 p-5 rounded-none bg-[#06060f] border border-indigo-500/15 flex flex-col gap-5 animate-in fade-in duration-200',
};
