export const solanaStyles = {
  card: 'rounded-none border border-neutral-800 bg-[#131315] p-6 sm:p-8 flex flex-col gap-6',
  header: 'flex items-center justify-between border-b border-neutral-800 pb-5',
  titleRow: 'flex items-center gap-3',
  badge: 'px-3 py-1 rounded-none text-[10px] font-bold uppercase tracking-widest',
  badgeConnected: 'bg-neutral-200 text-neutral-900 border border-neutral-200',
  badgeDisconnected: 'bg-neutral-900 text-neutral-500 border border-neutral-800',
  balanceCard: 'rounded-none bg-[#0a0a0a] p-5 border border-neutral-800',
  statLabel: 'text-[10px] uppercase font-bold text-neutral-500 tracking-wider',
  statValue: 'text-3xl font-bold text-neutral-200 tracking-tight mt-2',
  statSub: 'text-xs text-neutral-500 mt-1 truncate',
  formSection: 'flex flex-col gap-3 rounded-none bg-[#0a0a0a] p-5 border border-neutral-800',
  sectionTitle: 'text-xs font-bold text-neutral-300 uppercase tracking-wider',
  input: 'w-full rounded-none bg-[#050505] border border-neutral-800 px-4 py-3 text-sm text-neutral-300 placeholder-neutral-600 focus:outline-none focus:border-neutral-500 transition-colors',
  btnPrimary: 'w-full rounded-none bg-neutral-200 hover:bg-neutral-300 disabled:bg-neutral-900 disabled:text-neutral-600 px-4 py-3 text-sm font-bold text-neutral-900 transition-all cursor-pointer disabled:cursor-not-allowed',
  btnSecondary: 'w-full rounded-none bg-transparent hover:bg-neutral-900 disabled:bg-neutral-900 disabled:text-neutral-700 px-4 py-3 text-sm font-bold text-neutral-300 transition-all border border-neutral-800 cursor-pointer disabled:cursor-not-allowed',
  btnOutline: 'w-full rounded-none border border-neutral-700 hover:bg-neutral-800 disabled:opacity-50 px-4 py-3 text-sm font-bold text-neutral-300 transition-all cursor-pointer',
  txNotice: 'text-xs rounded-none p-4 bg-[#0a0a0a] border border-neutral-800 text-neutral-400 flex flex-col gap-1 break-all',
};
