export const solanaStyles = {
  card: 'rounded-2xl border border-neutral-800 bg-neutral-900/80 p-6 shadow-xl backdrop-blur-md flex flex-col gap-6',
  header: 'flex items-center justify-between border-b border-neutral-800 pb-4',
  titleRow: 'flex items-center gap-3',
  badge: 'px-2.5 py-1 rounded-full text-xs font-semibold uppercase tracking-wider',
  badgeConnected: 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/30',
  badgeDisconnected: 'bg-amber-500/10 text-amber-400 border border-amber-500/30',
  balanceCard: 'rounded-xl bg-neutral-950/70 p-4 border border-neutral-800/80',
  statLabel: 'text-xs uppercase font-medium text-neutral-400',
  statValue: 'text-2xl font-bold text-neutral-100 tracking-tight mt-1',
  statSub: 'text-xs text-neutral-500 mt-0.5 truncate',
  formSection: 'flex flex-col gap-3 rounded-xl bg-neutral-950/50 p-4 border border-neutral-800/60',
  sectionTitle: 'text-sm font-semibold text-neutral-200 flex items-center justify-between',
  input: 'w-full rounded-lg bg-neutral-900 border border-neutral-800 px-3 py-2 text-sm text-neutral-100 placeholder-neutral-500 focus:outline-none focus:border-purple-500 transition-colors',
  btnPrimary: 'w-full rounded-lg bg-purple-600 hover:bg-purple-500 disabled:bg-neutral-800 disabled:text-neutral-500 px-4 py-2.5 text-sm font-semibold text-white transition-all shadow-md active:scale-[0.99] cursor-pointer disabled:cursor-not-allowed',
  btnSecondary: 'w-full rounded-lg bg-neutral-800 hover:bg-neutral-700 disabled:bg-neutral-900 disabled:text-neutral-600 px-4 py-2.5 text-sm font-semibold text-neutral-200 transition-all border border-neutral-700/60 cursor-pointer disabled:cursor-not-allowed',
  btnOutline: 'w-full rounded-lg border border-purple-500/40 hover:bg-purple-500/10 disabled:opacity-50 px-4 py-2 text-xs font-medium text-purple-300 transition-all cursor-pointer',
  txNotice: 'text-xs rounded-lg p-2.5 bg-neutral-950/90 border border-neutral-800 text-neutral-400 flex flex-col gap-1 break-all',
};
