export const solanaStyles = {
  card: 'rounded-none border border-neutral-800/80 bg-[#0d0d12] p-6 sm:p-8 flex flex-col gap-6',
  header: 'flex items-center justify-between border-b border-violet-500/10 pb-5',
  titleRow: 'flex items-center gap-3',
  badge: 'px-3 py-1 rounded-none text-[10px] font-bold uppercase tracking-widest',
  badgeConnected: 'bg-gradient-to-r from-violet-500/20 to-fuchsia-500/20 text-violet-300 border border-violet-500/30',
  badgeDisconnected: 'bg-neutral-900 text-neutral-500 border border-neutral-800',
  balanceCard: 'rounded-none bg-[#07070f] p-5 border border-neutral-800/60 relative overflow-hidden before:absolute before:inset-0 before:bg-[radial-gradient(ellipse_at_top_right,rgba(168,85,247,0.06)_0%,transparent_60%)] before:pointer-events-none',
  statLabel: 'text-[10px] uppercase font-bold text-neutral-500 tracking-wider',
  statValue: 'text-3xl font-bold text-neutral-200 tracking-tight mt-2',
  statSub: 'text-xs text-neutral-500 mt-1 truncate',
  formSection: 'flex flex-col gap-3 rounded-none bg-[#07070f] p-5 border border-neutral-800/60',
  sectionTitle: 'text-xs font-bold text-neutral-400 uppercase tracking-wider',
  input: 'w-full rounded-none bg-[#050508] border border-neutral-800/80 px-4 py-3 text-sm text-neutral-300 placeholder-neutral-600 focus:outline-none focus:border-violet-500/50 focus:bg-[#07070f] transition-colors',
  btnPrimary: 'w-full rounded-none bg-gradient-to-r from-violet-600 to-fuchsia-600 hover:from-violet-500 hover:to-fuchsia-500 disabled:from-neutral-900 disabled:to-neutral-900 disabled:text-neutral-600 px-4 py-3 text-sm font-bold text-white transition-all cursor-pointer disabled:cursor-not-allowed',
  btnSecondary: 'w-full rounded-none bg-transparent hover:bg-sky-500/5 disabled:bg-neutral-900 disabled:text-neutral-700 px-4 py-3 text-sm font-bold text-neutral-300 hover:text-sky-300 transition-all border border-neutral-800 hover:border-sky-500/30 cursor-pointer disabled:cursor-not-allowed',
  btnOutline: 'w-full rounded-none border border-violet-500/30 hover:bg-violet-500/5 hover:border-violet-400/40 disabled:opacity-40 px-4 py-3 text-sm font-bold text-violet-300 hover:text-violet-200 transition-all cursor-pointer',
  txNotice: 'text-xs rounded-none p-4 bg-sky-500/5 border border-sky-500/15 text-neutral-400 flex flex-col gap-1 break-all',
};
